### ISSUE TITLE
wrong JSON data

### ISSUE THREAD

**Issue by gianlucabaldin** [apifytech/covid-19#107]
Hi,
I think today's update (12/05/2020) is broken, the dataset has 3 -and inconsistent- entities about today ==> https://api.apify.com/v2/datasets/CUdKmb25Z3HjkoDiN/items?format=json&clean=1

May you check please?
Thanks,
Gianluca

**Comment by remyoucef** [comment]
Thanks for the report.

The problem was on the source. First, they set a wrong value for **totalCases** [**178972**](https://github.com/pcm-dpc/COVID-19/commit/301e7bf864405a090be8f3f6ce785ee5c80996ed) (before it was **219814**), then set it to a string value [**"221216"**](https://github.com/pcm-dpc/COVID-19/commit/d09e62c2989fe761ef948f2ef80064554973dcd1) then correct it to a number value [ **221216**](https://github.com/pcm-dpc/COVID-19/commit/3f596ec8bc2e1cf8f8c368eadcbaa6313d2b758f).

@cybairfly can you remove the bad entries from the dataset and do some verification before pushing the data?

**Comment by gianlucabaldin** [comment]
Hi, any news?

**Comment by remyoucef** [comment]
Unfortunately, the author of the actor is busy.

@zpelechova can we fix this? If we do the dataset needs to be cleaned up and as consequences, its ID will change.

**Comment by zpelechova** [comment]
Hey all, sorry for the delay. We don't generally fix datasets, because of the ID shift. We provide scraping the data on the page, not cleaning the data. @gianlucabaldin Is it something you can do on your side, cleaning the data I mean? From what I understand from what @remyoucef wrote, the problem was on the source site?

**Comment by gianlucabaldin** [comment]
@zpelechova of course I technically do it by my own, BUT.. what about if another error will raise up in the future? 
..and I omit the fact to leave something like `if (date==12/05) then` in a production webapp would be embarrassing for the rest of my life :)

**Comment by zpelechova** [comment]
Yeah, I get that, but I am afraid if we change the dataset ID (we cannot change data within without doing so) it will be even more complicated to get the data for users, as they would have to look for the datasets with every change. Maybe you could upload the data to some ETL tool clean them automatically there and take the results from there for your app?
We have a price monitor app for 15 or so eshops and we run it through Keboola to clean the data before we use it in the app.

**Comment by gianlucabaldin** [comment]
ok, I get it.
I just fixed my app by my side, thanks anyway!

**Comment by zpelechova** [comment]
Sorry I couldnt be more help.
